# Generated by Django 5.1.5 on 2025-01-27 19:56

import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='default.png', upload_to=student.models.student_directory_path),
        ),
    ]
