# Generated by Django 5.1.5 on 2025-01-27 20:05

import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='Course_default.jpg', upload_to='Course_images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='profile_default.png', upload_to=student.models.student_directory_path),
        ),
    ]
