# Generated by Django 5.1.5 on 2025-01-27 20:24

import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='images\\default\\Course_default.jpg', upload_to=student.models.student_directory_path),
        ),
    ]
