# Generated by Django 5.1.5 on 2025-01-27 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_course_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='checked',
            new_name='active',
        ),
    ]
