# Generated by Django 5.1.5 on 2025-01-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_student_address_student_age_student_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, choices=[('Bangladesh', 'Bangladesh'), ('United States', 'United States'), ('United Kingdom', 'United Kingdom'), ('Germany', 'Germany')], max_length=50, null=True),
        ),
    ]
